trigger:
    - master
    
    pool:
      vmImage: 'windows-latest'
    
    variables:
      solution: 'src/Tandem.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Debug'
    
    steps:
      - template: templates/build-solution.yml